name: CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build CI
        run: |
          python3 -m pip install empy==3.3.4 pyserial future dronecan
          make arm_sdk_install
          make dsdl_generate
          make -j8

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: AM32-binaries
          path: |
            obj/*.hex
          retention-days: 7
